gText_Birch_Welcome::
	.string "היי! סליחה על ההמתנה!\p"
	.string "ברוכים הבאים לעולם הפוקימון!\p"
	.string "שמי הוא בירץ'.\p"
	.string "אבל כולם קוראים לי הפרופסור\n"
	.string "לפוקימון.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "זה מה שאנחנו מכנים פוקימון.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "העולם הזה מיושב לרווחה\n"
	.string "ביצורים הידועים בשם פוקימון.\p"
	.string "אנחנו בני האדם חיים לצד פוקימון, \n"
	.string "בזמני משחקי ידידות,\l"
	.string "ובזמנים כעובדים משותפים.\p"
	.string "ולפעמים, אנחנו קושרים יחדיו\n"
	.string "ונלחמים באחרים כמונו. \p"
	.string "אבל למרות הקירוב, אנחנו לא\n"
	.string "יודעים הרבה על פוקימון.\p"
	.string "למעשה, יש הרבה, הרבה\n"
	.string "סודות סביב פוקימון.\p"
	.string "כדי לחשוף תעלומות של פוקימון,\n"
	.string ".אני עושה מחקרים\l"
	.string ".זה מה שאני עושה\p"

gText_Birch_AndYouAre::
	.string "ואתם?$"

gText_Birch_BoyOrGirl::
	.string "הנך בן?\n"
	.string "או בת?$"

gText_Birch_WhatsYourName::
	.string "מצויין.\n"
	.string "מה שמך?$"

gText_Birch_SoItsPlayer::
	.string "אז שמך {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "!אה, אוקיי\p"
	.string "הנך {PLAYER}{KUN} שמגיע\n"
	.string ".לעיר מולדתי ליטלרוט\l"
	.string "!אני מבין את זה עכשיו\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "בסדר, הנך מוכן?\p"
	.string "ההרפתקאה שלך עומדת\n"
	.string ".להתחיל\p"
	.string "אזור אומץ, וזנק לתוך\n"
	.string "עולם הפוקימון, בו חלומות,\l"
	.string "הרפתקאות, וחברויות מצפים לך\p"
	.string "ובכן, אני מצפה לבואך מאוחר יותר.\n"
	.string "בוא למעבדת הפוקימון שלי.\p"
	.string "$"
